# Generated by Django 5.1.4 on 2026-09-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='batch',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(blank=True, choices=[('msc_computer_science', 'MSc Computer Science'), ('mca', 'MCA')], max_length=40),
        ),
    ]
