# Generated by Django 5.1.4 on 2026-09-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_legacy_notice_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic'), ('placement', 'Placement'), ('internship', 'Internship'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
