# Generated by Django 5.1.4 on 2026-09-17 20:15

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementapplication',
            name='resume',
            field=models.FileField(blank=True, upload_to='resumes/', validators=[core.validators.validate_resume_extension, core.validators.validate_file_size]),
        ),
        migrations.CreateModel(
            name='PlacementQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_questions', to='placement.placementdrive')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlacementAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='placement.placementapplication')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='placement.placementquestion')),
            ],
            options={
                'unique_together': {('application', 'question')},
            },
        ),
    ]
