# Generated by Django 5.1.4 on 2026-09-18 05:28

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_placementapplication_resume_placementquestion_and_more'),
        ('students', '0002_studentprofile_batch_studentprofile_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150)),
                ('job_role', models.CharField(max_length=150)),
                ('round_type', models.CharField(choices=[('aptitude_test', 'Aptitude Test'), ('coding_test', 'Coding Test'), ('technical_test', 'Technical Test'), ('technical_interview', 'Technical Interview'), ('hr_interview', 'HR Interview'), ('group_discussion', 'Group Discussion'), ('placement_drive', 'Placement Drive'), ('internship_interview', 'Internship Interview'), ('other', 'Other')], max_length=30)),
                ('date', models.DateField()),
                ('feedback', models.TextField()),
                ('questions_asked', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('difficult', 'Difficult')], max_length=10)),
                ('additional_comments', models.TextField(blank=True)),
                ('questions', models.FileField(blank=True, null=True, upload_to='placement_feedback/questions/', validators=[core.validators.validate_question_file_extension, core.validators.validate_file_size])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_feedback', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_feedback', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
