# Generated by Django 5.1.4 on 2026-09-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0004_alter_placementapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('test_scheduled', 'Test Scheduled'), ('test_completed', 'Test Completed'), ('interview_scheduled', 'Interview Scheduled'), ('applied', 'Applied'), ('interview', 'Interview'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted')], default='applied', max_length=20),
        ),
    ]
