# Generated by Django 6.1.1 on 2026-09-12 08:26

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('assistant_professor', 'Assistant Professor'), ('associate_professor', 'Associate Professor'), ('professor', 'Professor'), ('hod', 'Head of Department')], default='assistant_professor', max_length=30)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/', validators=[core.validators.validate_image_extension, core.validators.validate_file_size])),
                ('specialization', models.CharField(blank=True, max_length=300)),
                ('bio', models.TextField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty', to='core.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name'],
            },
        ),
    ]
