# Generated by Django 5.1.4 on 2026-09-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('placement_officer', 'Placement Officer'), ('alumni', 'Alumni'), ('admin', 'Administrator')], default='student', max_length=25),
        ),
    ]
