# Generated by Django 6.1.1 on 2026-09-12 08:26

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('research_area', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('required_skills', models.CharField(blank=True, max_length=500)),
                ('students_required', models.PositiveSmallIntegerField(default=1)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('expected_outcome', models.TextField(blank=True)),
                ('application_deadline', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_opportunities', to='faculty.facultyprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('authors', models.CharField(help_text='Comma separated author names', max_length=400)),
                ('research_area', models.CharField(blank=True, max_length=150)),
                ('paper_type', models.CharField(choices=[('research', 'Research Paper'), ('conference', 'Conference Paper'), ('publication', 'Publication'), ('journal', 'Journal'), ('report', 'Project Report')], default='research', max_length=20)),
                ('publication_year', models.PositiveIntegerField()),
                ('abstract', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='research_papers/', validators=[core.validators.validate_document_extension, core.validators.validate_file_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='faculty.facultyprofile')),
                ('students', models.ManyToManyField(blank=True, related_name='research_papers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publication_year', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(blank=True, related_name='research_teams', to='students.studentprofile')),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='research.researchopportunity')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_of_interest', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_applications', to='students.studentprofile')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='research.researchopportunity')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('student', 'opportunity')},
            },
        ),
    ]
