# Generated by Django 5.1.4 on 2026-09-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationpreference_emailnotificationlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreference',
            name='event_emails',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='research_emails',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='rlabs_emails',
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('important', 'Important'), ('urgent', 'Urgent')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='career_resource_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='feedback_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emailnotificationlog',
            name='notification_type',
            field=models.CharField(choices=[('placement', 'Placement'), ('internship', 'Internship'), ('feedback', 'Feedback'), ('career_resource', 'Career Resource'), ('achievement', 'Achievement'), ('announcement', 'Announcement')], default='announcement', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('placement', 'Placement'), ('internship', 'Internship'), ('feedback', 'Feedback'), ('career_resource', 'Career Resource'), ('alumni', 'Alumni'), ('achievement', 'Achievement'), ('announcement', 'Announcement')], default='announcement', max_length=20),
        ),
    ]
